const services =[
    {
id: 1,
Name: "Netflix",
Type: "Vpn",
imageUrl:"images/Netflixlogo.jpeg",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 2,
Name: "Express",
Type: "Vpn",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 3,
Name: "Nord",
Type: "Vpn",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 4,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 5,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 6,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 7,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 8,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 9,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 10,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 11,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 12,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 13,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 14,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 15,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 16,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 17,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 18,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 19,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},
    {
id: 20,
Name: "Netflix",
Type: "streamingService",
Description: "Descriptionsssssssssssssssssssssssssss",
},

]